# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2

updates:

  - package-ecosystem: "pip"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
