#!/bin/sh

set -e
set -u

case "${TOXENV}" in
    *-pypy*)
        echo "Installing PyPy..."

        PYENV_ROOT="${HOME}/.pyenv";

        rm -rf "${PYENV_ROOT}";
        git clone "https://github.com/pyenv/pyenv" "${PYENV_ROOT}";

        pyenv="${PYENV_ROOT}/bin/pyenv";

        set +e
        set +u
        eval "$("${pyenv}" init -)";
        set -e
        set -u

        "${pyenv}" install "pypy-${PYPY_VERSION}";
        "${pyenv}" global "pypy-${PYPY_VERSION}";

        echo "Python: $(type python)";
        python -V;
        ;;
esac;

pip install tox coverage codecov;
