#!/bin/sh

set -e
set -u
set -x

case "${TOXENV}" in
    *-pypy*)
        echo "Installing PyPy..."

        PYENV_ROOT="${HOME}/.pyenv";

        rm -rf "${PYENV_ROOT}";
        git clone "https://github.com/pyenv/pyenv" "${PYENV_ROOT}";

        pyenv="${PYENV_ROOT}/bin/pyenv";

        eval "$("${pyenv}" init -)";

        echo "1";

        pyenv install "pypy-${PYPY_VERSION}";

        echo "2";

        pyenv global "pypy-${PYPY_VERSION}";

        echo "Python: $(type python)";
        python -V;
        ;;
esac;

pip install tox coverage codecov;
