#!/bin/sh

#
# Work around bugs in mypy by filtering out false positive error messages.
#

set -e
set -u

tmp="$(mktemp -t mypy.XXXX)";

#
# Filter out messages from mypy that are not actual errors.
#
# Notes:
#
# * mypy notices trial's use of a skip marker attribute on functions and
#   complains that it's not part of a function object's interface, so we
#   ignore: has no attribute "skip". Same with "todo".
#
# * Filters applied only to specific files are things to fix in either Klein or
#   in mypy.
#
# * "type alias is invalid in runtime context" is a bug in mypy:
#   https://github.com/python/mypy/issues/5354
#
# * We run mypy with disallow_untyped_defs=True to require that type
#   annotations are used, but we ignore the errors for files that are not yet
#   participating.
#

mypy "$@"      \
    | grep -v  \
        -e ': error: The type alias to [A-Za-z]* is invalid in runtime context'                                              \
        -e '^src/klein/_app.py:[0-9:]*: error: Function is missing a type annotation'                                        \
        -e '^src/klein/_decorators.py:[0-9:]*: error: Function is missing a type annotation'                                 \
        -e '^src/klein/_iapp.py:[0-9:]*: error: Function is missing a type annotation'                                       \
        -e '^src/klein/_plating.py:.* error: Function is missing a type annotation'                                          \
        -e '^src/klein/_plating.py:[0-9:]*: error: Need type annotation for '                                                \
        -e '^src/klein/_resource.py:[0-9:]*: error: Function is missing a type annotation'                                   \
        -e '^src/klein/test/_trial.py:[0-9:]*: error: Function is missing a type annotation'                                 \
        -e '^src/klein/test/py3_test_resource.py:[0-9:]*: error: Function is missing a type annotation'                      \
        -e '^src/klein/test/test_app.py:[0-9:]*: error: Function is missing a type annotation'                               \
        -e '^src/klein/test/test_plating.py:[0-9:]*: error: Function is missing a type annotation'                           \
        -e '^src/klein/test/test_plating.py:[0-9:]*: error: Need type annotation for '                                       \
        -e '^src/klein/test/test_resource.py:[0-9:]*: error: Function is missing a type annotation'                          \
        -e '^src/klein/test/util.py:[0-9:]*: error: Function is missing a type annotation'                                   \
        > "${tmp}" || true;

sort < "${tmp}";

if grep -e ": error: " "${tmp}" > /dev/null; then
  exit 1;
fi;
