#!/bin/sh

set -e
set -u

case "${TOXENV}" in
    *-py2*|*-pypy*)
        export COVERAGE_OMIT="py3_*";
        ;;
esac;

case "${TOXENV}" in
    *-pypy*)
        pyenv_root="${HOME}/.pyenv";
        pyenv="${pyenv_root}/bin/pyenv";
        eval "$("${pyenv}" init -)";
        ;;
esac;

exec "$@";
