#!/bin/sh

set -e
set -u

case "${TOXENV}" in
    *-py2*|*-pypy*)
        COVERAGE_OMIT="py3_*";
        # Fall through
    *-pypy*)
        PYENV_ROOT="${HOME}/.pyenv";
        pyenv="${PYENV_ROOT}/bin/pyenv";
        eval "$("${pyenv}" init -)";
        ;;
esac;

exec "$@";
